//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Jugador
    {
        [DataMember]
        public int idjugador { get; set; }
        [DataMember]
        public Nullable<int> idequipo { get; set; }
        [DataMember]
        public string nombre { get; set; }
        [DataMember]
        public Nullable<double> estatus { get; set; }
        [DataMember]
        public string posicion { get; set; }
        [DataMember]
        public Nullable<int> edad { get; set; }
        [DataMember]
        public string foto { get; set; }
        [DataMember]
        public virtual Equipo Equipo { get; set; }
    }
}
